PQJiraInt1/src/objects/JIRA_Watcher__c.object
<CustomObject>
    <description>associate users with JIRA Issues</description>
    <fields>
        <fullName>Issues__c</fullName>
        <label>JIRACXIssue</label>
        <referenceTo>JIRACXIssue__c</referenceTo>
        <relationshipLabel>JIRA Watchers</relationshipLabel>
        <relationshipName>JIRA_Watchers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SFUsers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Salesforce users watching this JIRA Issue</description>
        <inlineHelpText>Salesforce users watching this JIRA Issue</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>JIRA_Watchers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>JIRA Watcher</label>
    <nameField>
        <label>JIRA Watcher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JIRA Watchers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PQJiraInt1/src/objects/JIRACXIssue__c.object
<CustomObject>
    <description>SF Copy of JIRA Issue related to Salesforce Client Cloud Cases</description>
    <label>JIRACXIssue</label>
    <nameField>
        <label>JIRACXIssue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JIRACXIssues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PQJiraInt1/src/classes/JIRACXIssueWrapper.cls
public class JIRACXIssueWrapper {

    private JIRACXIssue__c issue {get; set;}
    private boolean collapsed {get; set;}
    private boolean isWatching {get; }
        
    public JIRACXIssue__c getIssue(){
        return issue;
    }
    public void setIssue(JIRACXIssue__c inIssue){
        this.issue = inIssue;
    }
    public boolean getCollapsed(){
        system.debug('getting Collapsed - ' + this.collapsed);
       return this.collapsed;
    }
    public void setCollapsed(boolean newCollapse){
        system.debug('Setting collapsed - ' + newCollapse);
        this.collapsed = newCollapse;
    }
    public PageReference toggleCollapse(){
        system.debug('toggle collapse to - ' + !this.collapsed);
        setCollapsed(!this.collapsed);
        return null;
    }
    public JIRACXIssueWrapper(JIRACXIssue__c inIssue, boolean inCollapse){
        this.issue= inIssue;
        this.collapsed = inCollapse;
    }
    public boolean getIsWatching(){
    	for(JIRA_Watcher__c jw : issue.JIRA_Watchers__r ){
    		if (jw != null && jw.SFUsers__c != null && jw.SFUsers__r.id == UserInfo.getUserId()){
				return true;    			
    		}
    	}
    	return false;
    }
}