PQJiraInt1/src/objects/JIRA_Watcher__c.object
<CustomObject>
    <description>associate users with JIRA Issues</description>
    <fields>
        <fullName>Issues__c</fullName>
        <label>JIRACXIssue</label>
        <referenceTo>JIRACXIssue__c</referenceTo>
        <relationshipLabel>JIRA Watchers</relationshipLabel>
        <relationshipName>JIRA_Watchers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SFUsers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Salesforce users watching this JIRA Issue</description>
        <inlineHelpText>Salesforce users watching this JIRA Issue</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>JIRA_Watchers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>useChatter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Send Chatter notifications for JIRA issue updates</description>
        <inlineHelpText>Send Chatter notifications for JIRA issue updates</inlineHelpText>
        <label>useChatter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>useEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Send email notifications for JIRA issue updates</description>
        <inlineHelpText>Send email notifications for JIRA issue updates</inlineHelpText>
        <label>useEmail</label>
        <type>Checkbox</type>
    </fields>
    <label>JIRA Watcher</label>
    <nameField>
        <label>JIRA Watcher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JIRA Watchers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PQJiraInt1/src/objects/JIRACXIssue__c.object
<CustomObject>
    <description>SF Copy of JIRA Issue related to Salesforce Client Cloud Cases</description>
    <fields>
        <fullName>Account_Info__c</fullName>
        <label>Account Info</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_Behavior__c</fullName>
        <label>Actual Behavior</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_Result__c</fullName>
        <label>Actual Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Affected_Customers__c</fullName>
        <label>Affected Customers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Affected_UI__c</fullName>
        <label>Affected UI</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional/Academic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assignee__c</fullName>
        <description>Who is the JIRA issue assigned to</description>
        <inlineHelpText>Why the JIRA issue is assigned to</inlineHelpText>
        <label>Assignee</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Numbers__c</fullName>
        <label>Case Numbers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>JIRACreated__c</fullName>
        <description>Datetime the JIRA was created</description>
        <inlineHelpText>When the JIRA issue was created</inlineHelpText>
        <label>Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>JIRAKey__c</fullName>
        <description>The unique JIRA Key for the issue</description>
        <externalId>true</externalId>
        <inlineHelpText>The JIRA Project Key id for the JIRA issue</inlineHelpText>
        <label>JIRAKey</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>JIRAProject__c</fullName>
        <description>Project that the JIRA issue belongs to</description>
        <inlineHelpText>JIRA defined project name that the issue belongs to</inlineHelpText>
        <label>JIRAProject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JIRAStatus__c</fullName>
        <description>The status of the JIRA issue</description>
        <inlineHelpText>The status of the JIRA issue</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JIRAUpdated__c</fullName>
        <description>When the JIRA issue was last updated</description>
        <inlineHelpText>When the JIRA issue was last updated</inlineHelpText>
        <label>Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority of the JIRA Issue</description>
        <inlineHelpText>Priority of the issue in JIRA</inlineHelpText>
        <label>Priority</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <description>Resolution of the JIRA issue</description>
        <inlineHelpText>Resolution of the JIRA issue</inlineHelpText>
        <label>Resolution</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Root_Cause_Analysis_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Root Cause Analysis Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>JIRACXIssue</label>
    <nameField>
        <label>JIRACXIssue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JIRACXIssues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PQJiraInt1/src/objects/JIRACXIssueComment__c.object
<CustomObject>
    <description>Comments recorded in JIRA for an issue</description>
    <fields>
        <fullName>Author__c</fullName>
        <description>JIRA comment author</description>
        <inlineHelpText>JIRA comment author</inlineHelpText>
        <label>Author</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JIRACreatedDate__c</fullName>
        <description>JIRA comment creation date</description>
        <inlineHelpText>JIRA comment creation date</inlineHelpText>
        <label>JIRACreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>JIRAIssue__c</fullName>
        <label>JIRACXIssue</label>
        <referenceTo>JIRACXIssue__c</referenceTo>
        <relationshipLabel>JIRACXIssueComments</relationshipLabel>
        <relationshipName>JIRACXIssueComments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>JIRAKey__c</fullName>
        <description>External JIRA key for the issue owning this comment</description>
        <inlineHelpText>External JIRA key for the issue owning this comment</inlineHelpText>
        <label>JIRAKey</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>body__c</fullName>
        <description>JIRA Comment string</description>
        <inlineHelpText>JIRA comment string</inlineHelpText>
        <label>body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>JIRACXIssueComment</label>
    <nameField>
        <label>JIRACXIssueComment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JIRACXIssueComments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PQJiraInt1/src/classes/JIRACaseExtension.cls
global class JIRACaseExtension {
    private ApexPages.StandardController cont;
//    private final JIRAClientClouds__c jcc;
    public JIRAIssues jIssues {get;set;}
    public JIRACXField.JIRAField[] jfields;
    public ID caseId {get;set;}
    private Case sfCase {get; set;}

    public ID getCaseId(){ return this.caseId;}
    public void setCaseId(String inId) {this.caseId = inId;}
    
//    public JIRAIssues getJIssues(){ return this.jIssues;}
//    public void setJIssues(JIRAIssues ji) { this.jIssues = ji;}
    
    @RemoteAction
    global static PageReference refresh() {
       system.debug('in the refresh method');
       return null;
    }
    
    public PageReference returnURL {
        get;
        // *** setter is NOT being called ***
        set {
            returnURL = value;
            System.debug('value: '+value);
        }
    }
    
    
     // Constructor of this class. Note that a request will be sent to JIRA when this class is constructed.
    global JIRACaseExtension(ApexPages.StandardController stdController) {
        cont = stdController;
        sfCase = (Case)stdController.getRecord();
        System.debug('case is ' + sfCase.id);

    }

  //  global JIRACaseExtension(JIRACXIssueController caseController) {
   // }
    
    public PageReference loadCaseIssues() {
        String theCaseId;
        if(cont != null){
            theCaseId = ((Case)cont.getRecord()).id;
            theCaseId = theCaseId.Left(15);
        }else
            theCaseId = ApexPages.currentPage().getParameters().get('id');
        
       system.debug('the case is ' + theCaseId);
       sfCase = [SELECT id from Case where id = :theCaseId];
       
        if(sfCase != null){
            // do the remote login to JIRA
            JIRALogin jl = new JIRALogin();
            //jl.getAllProjects();
            
            system.debug('get the case JIRAs for ' + sfCase.Id);
            JIRACXIssue__c[] Objissues = jl.getJIRAbyCase(theCaseId);  // using the 15 character Id for ease of using the URL
            //updateAllIssues(Objissues);
            jIssues = new JIRAIssues();

            system.debug('Case referenced in ' + Objissues.size() + ' JIRAs');
            system.debug('Case Id is ' + theCaseId);
//            List<JIRACXIssue__c> sfIssues = [SELECT id, Account_Info__c, Actual_Behavior__c,Actual_Result__c,Affected_Customers__c,Affected_UI__c,Priority__c,
//                                            JIRACreated__c,description__c,Resolution__c,Summary__c,JIRAStatus__c,JIRAProject__c,JIRAUpdated__c,Assignee__c FROM JIRACXIssue__c WHERE Case_Numbers__c  like '%:theCaseId%'];
            List<JIRACXIssue__c> sfIssues = Database.query('SELECT id, name, JIRAKey__c, Case_numbers__c, Account_Info__c, Actual_Behavior__c,Actual_Result__c,Affected_Customers__c,Affected_UI__c,Priority__c, JIRACreated__c,description__c,Resolution__c,Summary__c,JIRAStatus__c,JIRAProject__c,JIRAUpdated__c,Assignee__c, Root_Cause_Analysis_Requested__c, (SELECT Author__c,JIRACreatedDate__c,body__c FROM JIRACXIssueComments__r ),(SELECT id,useChatter__c, useEmail__c, SFUsers__r.name, createddate FROM JIRA_Watchers__r) FROM JIRACXIssue__c WHERE Case_Numbers__c = :theCaseId');

			

			system.debug('sfIssues contains ' + sfIssues.size() + ' issues');
            for(JIRACXIssue__c ji : sfIssues) {
                if(ji != null){
                    jIssues.issues.add(new JIRACXIssueWrapper(ji, true));
                    
                    //system.debug('adding item to issues list');
                }
            }
            system.debug('SF has ' + jIssues.issues.size() + ' JIRAs related');
            //jfields = jl.getJIRAFields();
            
            try{
                //updateAllIssues();
    //            jl.getAllSerSolProjects();
           //     jl.getAllPQProjects();
            }
            catch(Exception ex) {
                System.Debug('Failed SerSol Test');
                System.debug(ex.getMessage());
            }    
        //jl.testAJIRAQuery('issue/createmeta?projectKeys=PUB&issuetypeIds=10102&expand=project.issuetypes.fields');
        }
		return null;
    }
      
    public  PageReference updateAllIssues(List<JIRACXIssue__c> updIssues) {
       system.debug('in updateAllIssues method');
        //List<JIRACXIssue__c> updIssues = new List<JIRACXIssue__c>();
        if(updIssues != null ){
//            for(JIRACXIssueWrapper jw : jIssues.issues){
//                if(jw != null){
/*            for(JIRACXIssue__c issue : updIssa)
                    JIRACXIssue__c ji = jw.getIssue();
                    system.debug('saving JIRA ' + ji.JIRAKey__c);
                    updIssues.add(ji);
                }
            }
*/            
            upsert updIssues JIRACXIssue__c.Fields.JIRAKey__c;
        }        
        return null;
    }

          
    // this doesn't belong here, just using for dev testing
    @RemoteAction
    global static boolean updateCaseJiras(){
       system.debug('in updateAllIssues method - ');
        JIRAIntegration__c jInt = JIRAIntegration__c.getInstance();
		DateTime lastUpdate = jInt.lastIssueRefreshAll__c;
        
        if(lastUpdate == null || lastUpdate > DateTime.now())
            lastUpdate = DateTime.now().addMinutes(-10);
        // do the remote login to JIRA
        JIRALogin jl = new JIRALogin();
        if(jl != null){
	        system.debug('updating all the JIRAs');
	        jl.getAllUpdateIssues(lastUpdate);
   
            // if updating the last update time:
            system.debug('saving lastUpdate - '+ lastUpdate);
            List<JIRAIntegration__c> updJInt = [Select Id, lastIssueRefreshAll__c From JIRAIntegration__c ]; 
            if(updJint.size() == 0){
                JIRAIntegration__c newJInt = new JIRAIntegration__c();
                newJInt.lastIssueRefreshAll__c = lastUpdate;
                insert newJInt;
            }else if (updJint.size() == 1) {
                updJInt[0].lastIssueRefreshAll__c = lastUpdate;
                update updJInt;
            }else{
                for(integer i=0; i<updJInt.size();i++)
                    updJInt[i].lastIssueRefreshAll__c = lastUpdate;
                update updJInt;                
            }
        }
        
        return true;
    }
}